Sources/KoSme_01 - Copy/KoSme_01/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import kosme.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
 #   url(r'^login/$', auth_views.login, {'template_name': 'kosme/login.html'}, name='login'),
  #  url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^kosme/',include('kosme.urls')),
   # url(r'^signup/$', kosme.views.signup, name='signup'),

]

Sources/KoSme_01 - Copy/kosme/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

app_name = 'kosme'

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^mainPage/',views.mainPage, name='mainPage'),
   # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^courses/$', views.courses, name='courses'),
    url(r'^course/(?P<pk_course>\d+)$', views.courseID, name='courseID'),
    #url(r'^course/(?P<pk_course>\d+)/lectures/$', views.lectures, name='lectures'),
    url(r'^course/(?P<pk_course>\d+)/lecture/(?P<pk_lect>\d+)$', views.lectureID, name='lectureID'),
    url(r'^course/(?P<pk_course>\d+)/lecture/create$', views.lectureCreate, name='lectureCreate'),
    url(r'^lecture/(?P<pk_course>\d+)/(?P<pk_lect>\d+)/delete', views.lectureIDDelete, name='lectureIDDelete'),
    url(r'^lecture/(?P<pk_course>\d+)/(?P<pk_lect>\d+)/edit$', views.lectureIDEdit, name='lectureIDEdit'),
    url(r'^results/(?P<pk_qiuz>\d+)$', views.results, name='results'),

    url(r'^quiz/$', views.quiz, name='quiz'),
    url(r'^logout/$', views.log_out, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^user/profile/$', views.profile, name="profile"),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^user/$', views.user_index, name="userIndex"),
    url(r'^user/class$', views.user_class, name="userClass"),
    url(r'^user/quiz_all/$', views.allQuizes, name="allQuizes"),
    url(r'^user/(?P<pk_course>\d+)/quiz/create$', views.quiz, name='quiz'),
    url(r'^user/statistics$', views.user_statistics, name='userStatistics'),
    url(r'^user/(?P<pk_quiz>\d+)/delete', views.delete_quiz, name="deleteQuiz"),
    url(r'^user/(?P<pk_quiz>\d+)/show$', views.show_quiz, name="showQuiz"),
    url(r'^user/(?P<pk_quiz>\d+)/edit$', views.edit_quiz, name="editQuiz")

]

Sources/KoSme_01 - Copy/kosme/models.py
from django.db import models
from django.contrib.auth.models import User

import django.utils.timezone as timezone

class Profile(models.Model):
   user = models.OneToOneField('auth.User')
   User._meta.get_field('email')._unique = True
   is_blocked = models.BooleanField(default=True)
   is_teacher = models.BooleanField(default=False)
   def __str__(self):
       return "%s %s %s" % (self.user, self.is_blocked, self.is_teacher)


class Teacher(models.Model):
   user = models.OneToOneField('auth.User')
   User._meta.get_field('email')._unique = True

   def __str__(self):
       return "%s %s %s " % (self.user, self.user.first_name, self.user.last_name)


class SchoolClass(models.Model):
   name = models.CharField(max_length=30, unique=True)
   class Meta:
        verbose_name_plural = "School classes"
   def __str__(self):
       return "%s " % (self.name)


class Course(models.Model):
       name = models.CharField(max_length=30)
       author = models.ForeignKey(Teacher,null=True)
       classes = models.ManyToManyField(SchoolClass)

       class Meta:
           verbose_name_plural = "Courses"

       def __str__(self):
           return self.name

class Student(models.Model):
    user = models.OneToOneField('auth.User')
    User._meta.get_field('email')._unique = True
    schoolClass = models.ForeignKey(SchoolClass, null=True)
    def __str__(self):
        return "%s %s " % (self.user.first_name, self.user.last_name)


class Quiz(models.Model):
    name = models.CharField(max_length=30)
    data = models.TextField(max_length=4000)
    course = models.ForeignKey(Course, null=True)
    class Meta:
        verbose_name_plural = "Quizes"
    def __str__(self):
        return "%s " % (self.name)

class Result(models.Model):
    student = models.ForeignKey(Student)
    points = models.IntegerField(default=0)
    quiz = models.ForeignKey(Quiz)



class Lecture(models.Model):
       name = models.CharField(max_length=100)
       course = models.ForeignKey(Course,null=True)
       link =  models.CharField(max_length = 250,null=True)
       date = models.DateField(default=timezone.now())
       def __str__(self):
           return self.name


# Create your models here.

Sources/KoSme_01 - Copy/kosme/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    #school_class = forms.ModelChoiceField(queryset= SchoolClass.objects.values_list('name', flat=True))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username', 'email','first_name', 'last_name', 'password1', 'password2')

Sources/KoSme_01 - Copy/kosme/views.py
from kosme.forms import SignUpForm, UserForm
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt

import requests

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from collections import defaultdict


def getTeacher(request):
    return Teacher.objects.get(user_id=request.user.profile.user_id)

def isAuthor(teacher,course):
    return course.author_id == teacher.id

SERVERHOST = "http://127.0.0.1:8800"

def saveToServer(type,id,dataToSave):
    link = createLink(type=type,id=id)
    r = requests.put(url=link, data=dataToSave)


def createLink(type,id):
    return SERVERHOST +'/'+ type + str(id)

def getData(link):
    return requests.get(url=link).text

@login_required(login_url='kosme:mainPage')
@csrf_exempt
def lectureIDEdit(request,pk_course,pk_lect):
    course = Course.objects.filter(id=pk_course)
    if not course:
        return render(request,'kosme/404Page.html', {'error_message': "Такого предмету не існує"})
    course = course[0]
    teacher = getTeacher(request)
    if not isAuthor(teacher,course):
        return render(request,'kosme/404Page.html', {'error_message': "Це не ваш предмет"})
    if request.user.profile.is_teacher:
        if request.method == "GET":

                lectures = Lecture.objects.filter(id=pk_lect)
                if not lectures:
                    return render(request,'kosme/404Page.html', {'error_message': "Такої лекції не існує."})
                lecture = lectures[0]
                return render(request,'kosme/lectureEdit.html', {'lecture': lecture})

        if request.method == 'POST':
            return redirect('kosme:courses')

    else:
        return redirect('kosme:mainPage')



@login_required(login_url='kosme:mainPage')
@csrf_exempt
def lectureCreate(request,pk_course):
    course = Course.objects.filter(id=pk_course)
    if not course:
        return render(request,'kosme/404Page.html', {'error_message': "Такого предмету не існує"})
    course = course[0]
    teacher = getTeacher(request)
    if not isAuthor(teacher,course):
        return render(request,'kosme/404Page.html', {'error_message': "Це не ваш предмет"})
    if request.user.profile.is_teacher:
        if request.method == "GET":
            return render(request,'kosme/lectureCreate.html')

        if request.method == 'POST':
            dataToSave = request.POST.get("HTMLtoPDF", "").encode("utf-8")
            fileName = request.POST.get("fileName", "")
            lecture = Lecture()
            lecture.name = fileName
            lecture.course_id = pk_course
            lecture.save()
            lecture.link = createLink('lecture',lecture.id)
            lecture.save()
            saveToServer('lecture',lecture.id,dataToSave)
            return redirect('kosme:mainPage')
    else:  return redirect('kosme:mainPage')

@login_required(login_url='kosme:mainPage')
def lectureID(request,pk_course,pk_lect):
    lecture = Lecture.objects.filter(id=pk_lect)
    if not lecture:
        return render(request,'kosme/404Page.html', {'error_message': "Такої лекції не існує"})
    lecture = lecture[0]
    return render(request,'kosme/lectureShow.html', {'lecture': lecture})

@login_required(login_url='kosme:mainPage')
def lectureIDDelete(request,pk_course, pk_lect):
    course = Course.objects.filter(id=pk_course)
    if not course:
        return render(request,'kosme/404Page.html', {'error_message': "Такого предмету не існує"})
    Lecture.objects.filter(id=pk_lect)[0].delete()
    return redirect("kosme:courseID",pk_course)



@login_required(login_url='kosme:mainPage')
def courseID(request,pk_course):
    course = Course.objects.filter(id=pk_course)
    if not course:
        return render(request,'kosme/404Page.html', {'error_message': "Такого предмету не існує"})
    course = course[0]
    if request.user.profile.is_teacher:
        teacher = getTeacher(request)
        if not course.author_id == teacher.id:
            return render(request,'kosme/404Page.html', {'error_message': "Це не ваш предмет"})
        all_lectures = Lecture.objects.filter(course_id = pk_course)
        all_quizes = Quiz.objects.filter(course_id=pk_course)
    else:
        all_lectures = Lecture.objects.filter(course_id=pk_course)
        all_quizes = Quiz.objects.filter(course_id=pk_course)
    return render(request,'kosme/allLectures.html', {"all_quizes": all_quizes,'all_lectures': all_lectures,'course_id': pk_course , 'user':request.user})


@login_required(login_url='kosme:mainPage')
def courses(request):
    if request.user.profile.is_blocked:
        return redirect("kosme:mainPage")
    else:
        if request.user.profile.is_teacher:
            teacher = Teacher.objects.get(user_id = request.user.profile.user_id)
            all_courses = Course.objects.filter(author_id= teacher.id)
            return render(request,'kosme/allCourses.html', {'all_courses': all_courses, 'user':request.user})
        else:
            student = Student.objects.filter(user_id=request.user.profile.user_id)[0]
            schoolClass = SchoolClass.objects.filter(id=student.schoolClass.id)[0]
            all_courses = Course.objects.all()
            courses =[]
            for course in all_courses:
                if schoolClass in course.classes.all():
                    courses.append(course)
            return render(request,'kosme/allCourses.html', {'all_courses': courses, 'user': request.user})

@login_required(login_url='kosme:mainPage')
def results(request,pk_qiuz):
    if request.user.profile.is_blocked:
        return redirect("kosme:mainPage")
    else:
        if request.user.profile.is_teacher:
            results = Result.objects.filter(quiz_id=pk_qiuz)
            return render(request,'kosme/results.html', {'all_results': results})
        else:

            return render(request,'kosme/404Page.html', {'error_message': "Ви не викладач"})



#___________________________________________________________________

def signup(request):
    if request.user.is_authenticated():
        return redirect('kosme:userIndex')
    else:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = User.objects._create_user(username, request.POST['email'], raw_password,
                                                 first_name=request.POST['first_name'],
                                                 last_name=request.POST['last_name'])
                profile = Profile(user=user)
                profile.save()
                return redirect('kosme:signin')
        else:
            form = SignUpForm()
        return render(request, 'kosme/signup.html', {'form': form})

@login_required(login_url='kosme:mainPage')
def profile(request):
    return render(request, 'kosme/profile.html')


@login_required(login_url='kosme:mainPage')
def user_index(request):
    return render(request, 'kosme/userIndex.html')


@login_required(login_url='kosme:mainPage')
def log_out(request):
    logout(request)
    return redirect('kosme:mainPage')


@login_required(login_url='kosme:mainPage')
def user_class(request):
    students = None
    cname = None
    if Student.objects.filter(user=request.user).exists():
        mclass = Student.objects.get(user=request.user).schoolClass
        students = Student.objects.filter(schoolClass=mclass)
        cname = mclass.name
    return render(request, 'kosme/userClass.html', context={'students': students, 'cname': cname})


def signin(request):
    if request.user.is_authenticated():
            return redirect('kosme:userIndex')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            raw_password = request.POST['password']
            if User.objects.filter(username=username).exists():
                user = User.objects.get(username=username)
                if Profile.objects.filter(user=user).exists():
                    if not user.profile.is_blocked:
                            user = authenticate(username=username, password=raw_password)
                            if user is not None:
                                login(request, user)
                                return redirect('kosme:userIndex')
                            else:
                                messages.error(request, "Введено неправильний пароль")
                                return redirect('kosme:signin')
                    else:
                        messages.error(request, "Чекайте підтвердження від адміністратора")
                        return redirect('kosme:signin')
                else:
                    return render_to_response('kosme/404Page.html',
                                              {'error_message': "Виникла помилка аккаунта. Зверніться до адміністратора."})
            else:
                messages.error(request, "Неправильні дані. Користувача з заданим логіном не існує.")
                return redirect('kosme:signin')

        else:
            form = UserForm()
            return render(request, 'kosme/login.html', {'form': form})


def mainPage(request):
    if request.user is not None:
        if request.user.is_authenticated():
                return redirect('kosme:userIndex')
    return render(request,'kosme/mainPage.html')

#______________________________________________________#

@login_required(login_url='kosme:mainPage')
def quiz(request, pk_course):
    if not request.user.profile.is_teacher:
        return redirect('kosme:mainPage')
    else:
        if request.method == 'POST':
            mdata = request.POST["Json"].encode('utf-8')
            name = request.POST["quiz_name"].encode('utf-8')

Sources/KoSme_01 - Copy/kosme/templates/kosme/404Page.html
{% extends 'kosme/base.html' %}
{% load i18n %}
{% block content %}
    <div class="container">

   <h1 class="text-center">KoSme</h1>

    <div class="text-center btn-group btn-group-justified">
        <p>{{ error_message }}</p>
    </div>
 </div>
{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/allCourses.html
{% extends 'kosme/base.html' %}
{% load i18n %}
{% block content %}
<ul class="list-group">
   {% for course in all_courses %}
       <li  class="list-group-item">
           <a class="btn btn-info" role="button" href = "{% url 'kosme:courseID' course.id %}"> {{ course.name }}</a>

       </li>
    {% endfor %}
</ul>
{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/allLectures.html
{% extends 'kosme/base.html' %}
{% load i18n %}
{% block content %}
    <h1>Лекції</h1>
<ul class="list-group">
   {% for lecture in all_lectures %}
       <li  class="list-group-item">
           <h4> {{ lecture.name }}
           <a class="btn btn-info" role="button" href = "{% url 'kosme:lectureID'  course_id  lecture.id  %}"> {{ lecture.name }}</a>
         {% if user.profile.is_teacher %}  <a class="btn btn-warning" role="button" href = "{% url 'kosme:lectureIDEdit' course_id lecture.id  %}"> РЕДАГУВАТИ</a>
           <a class="btn btn-danger" role="button" href = "{% url 'kosme:lectureIDDelete' course_id lecture.id  %}"> ВИДАЛИТИ </a>
       {% endif %}
        </h4>
       </li>
    {% endfor %}
</ul>
    <h1>Тести</h1>
    <ul>   {% for quiz in all_quizes %}
       <li>
           <h4> {{ quiz.name }}
           {% if user.profile.is_teacher %}
               <a class="btn btn-info" role="button" href =  "{% url 'kosme:editQuiz'  quiz.id  %}"> РЕДАГУВАТИ</a>
               <a class="btn btn-warning" role="button"  href =  "{% url 'kosme:deleteQuiz'  quiz.id %}"> ВИДАЛИТИ</a>
               <a class="btn btn-info" role="button"  href =  "{% url 'kosme:results'  quiz.id %}"> Статистика</a>

            {% else %}
               <a class="btn btn-warning" role="button"  href ="{% url 'kosme:showQuiz'  quiz.id  %}"> {{ quiz.name }}</a>
            {% endif %}
           </h4>

       </li>
    </ul>
    {% endfor %}
    <br><br>
    <br><br>
    {% if user.profile.is_teacher %}
                <a class="btn btn-danger" role="button" href="{% url 'kosme:lectureCreate' course_id %}">Створити нову лекцію</a>
                <a class="btn btn-danger" role="button" href="{% url 'kosme:quiz' course_id %}">Створити новий тест </a>

    {% endif %}

{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/allQuizes.html
{% extends 'kosme/quiz_base.html' %}
{% load i18n %}
{% block content %}

   {% for quiz in all_quizes %}
       <li>
           <h3> {{ quiz.name }}</h3>
           {% if request.user.profile.is_teacher %}
               <a  href =  "{% url 'kosme:editQuiz'  quiz.id  %}"> РЕДАГУВАТИ</a>
               <a  href =  "{% url 'kosme:deleteQuiz'  quiz.id  %}"> ВИДАЛИТИ</a>
            {% else %}
               <a  href ="{% url 'kosme:showQuiz'  quiz.id  %}"> {{ quiz.name }}</a>
            {% endif %}
       </li>
            <a href="{% url 'kosme:quiz' %}">Create new </a>
    {% endfor %}




{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>KoSme school</title>
    {% load staticfiles %}
    {% load i18n %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'kosme/style.css' %}">

    <script type="text/javascript" src="{% static 'ckeditor/ckeditor.js' %}"></script>
        <script type="text/javascript" src="{% static 'kosme/js.js' %}"></script>


    <script src="https://code.jquery.com/jquery-1.10.1.js"></script>

     <meta property="og:url" content="https://lipis.github.io/flag-icon-css/" />
   <style>

   </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class = "container-fluid">
            <div class ="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div  class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a  href="{% url 'kosme:mainPage' %}">
                            <span class="glyphicon  glyphicon-home" aria-hidden="true"></span>&nbsp;Основна сторінка</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li >
                            <a  href="{% url 'kosme:courses' %}">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;Предмети</a>
                        </li>
                        <li>
                            <a  href="{% url 'kosme:profile' %}">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Профіль</a>
                        </li>
                        <li>
                            <a  href="{% url 'kosme:logout' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Вийти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>



        </div>
    </nav>
  <main>

    {% block content %}
    {% endblock %}



  </main>
</body>
</html>

Sources/KoSme_01 - Copy/kosme/templates/kosme/lectureCreate.html
{% extends 'kosme/base.html' %}
{% load i18n %}

{% block content %}
{#onSubmit="return saveDocumentByName(this.sub)"#}
    <form id="form" method="post"  class="form-group">
           <textarea id="editor1" name="editor1" style="height: 70em">Вводьте лекцію тут)</textarea>

             {% csrf_token %}
              <label for="fileName">Назва лекції:</label>
              <input class="form-control" name="fileName" id="fileName" required>
              <input  id="HTMLtoPDF" name="HTMLtoPDF" hidden="hidden">
             <br>
            <button name="sub" type="submit"  class="btn btn-primary"> Зберігти </button>
            </form>
        </form>


       <script type="text/javascript">
        CKEDITOR.replace( 'editor1' );
        timer = setInterval(updateDiv,100);
        function updateDiv(){
            var editorText = CKEDITOR.instances.editor1.getData();
               var fileDisplayArea = document.getElementById('HTMLtoPDF');
            fileDisplayArea.value = editorText;
        }
    </script>


{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/lectureEdit.html
{% extends 'kosme/base.html' %}
{% load i18n %}

{% block content %}

    <form  method="post" class="form-group"  >

           <textarea id="editor1" name="editor1">Вводьте лекцію тут)</textarea>

             {% csrf_token %}
             <input id="HTMLtoPDF" name="HTMLtoPDF" hidden="hidden">
             <br>
            <button name = "sub" class="btn btn-primary" onclick="saveDocument({{ lecture.link }})" type="submit"> Закрити редагування </button>
            </form>
    </form>
         <p id="link" hidden="hidden"  > {{ lecture.link}}</p>
         <button  id="myCheck" hidden="hidden"   onclick="setLectureText('{{ lecture.link }}')" > Show example </button>
            <script>window.onload =  document.getElementById("myCheck").click();</script>



       <script type="text/javascript">
        CKEDITOR.replace( 'editor1' );
        timer = setInterval(updateDiv,100);
        function updateDiv(){
            updateText()
            var fileDisplayArea = document.getElementById('HTMLtoPDF');
            fileDisplayArea.value = CKEDITOR.instances.editor1.getData();
        }
    </script>


{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/lectureShow.html
{% extends 'kosme/base.html' %}
{% load i18n %}
{% block content %}

  <h1 >{{ lecture.name }}</h1>

   <pre style="margin: 5%; width: 90%; white-space: pre-wrap;
     white-space: -moz-pre-wrap;
     white-space: -pre-wrap;
     white-space: -o-pre-wrap;
     word-wrap: break-word;
" id="fileDisplayArea" value = {{ text }}  onload="myFunction('{{ text }}')"  > </pre>

        <button id="myCheck" hidden="hidden"  type="button" onclick="uploadLectureText('{{ lecture.link }}')" > Show example </button>
        <script>window.onload =  document.getElementById("myCheck").click();</script>

{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/login.html
{% extends 'kosme/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
  <h2>Увійти</h2>
    <ul class="messages">
        {% for message in messages %}
            {% if message.tags  == 'error'%}
                <li class="list-group-item list-group-item-danger"> {{ message }}</li>
            {% else %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
            {% endif %}
        {% endfor %}
    </ul>
  <form method="post" class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Увійти</button>
  </form>
    </div>
{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/mainPage.html
{% extends 'kosme/base.html' %}
{% load i18n %}
{% block content %}

   <h1 class="text-center">KoSme school main page</h1>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="text-center btn-group btn-group-justified">
    <a href="{% url 'kosme:signin' %}" class="btn btn-primary">Увійти</a>
    <a href="{% url 'kosme:signup' %}" class="btn btn-primary">Зареєструватись</a>

    </div>

{% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/profile.html
    {% extends 'kosme/base.html'%}
    {% load i18n %}
    {% block title %}User info{% endblock %}

    {% block content %}
    <ul class="list-group">
        <li class="list-group-item">
            <h3 class="text-center"> Персональна інформація </h3>
        </li>
    </ul>

        <ul class="list-group" >
            <li class="list-group-item "> Логін :  {{ user.username}}</li>
            <li class="list-group-item"> Ім'я:  {{ user.first_name}}</li>
            <li class="list-group-item">Прізвище: {{user.last_name}}</li>
            <li class="list-group-item"> email: {{ user.email }}</li>
        </ul>
    {% endblock %}

Sources/KoSme_01 - Copy/kosme/templates/kosme/quizEdit.html
{% extends 'kosme/quiz_base.html' %}
{% load i18n %}
 {% load staticfiles %}
{% block content %}
    <body>
    <h1>Редагування тестів</h1>
        <div class="form-group">
            <label for="quiz_name" class="col-sm-3 control-label">Введіть назву тесту:</label>
                <div class="col-sm-9">
                    <input name="name" id="quiz_name" value="{{ qname }}" class="form-control" required>
                </div>
        </div>
        <br/>
        <br/>
        <div id="surveyContainer">
            <div id="editorElement"></div>
        </div>
        <input id="mainJSON" name="mainJSON" type="hidden" value="{{ mainJSON }}" />

        <script type="text/javascript" src="{% static 'kosme/quiz_edit.js' %}"></script>

    </body>
{% endblock %}